version: '3'

services:
  #
  # Portainer docker admin GUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  postgis:
    image: postgis/postgis:${POSTGIS_VERSION_TAG:-16-3.4}
    container_name: ${COMPOSE_PROJECT_NAME}_postgis
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - "PGUSER=${POSTGRES_USER:-gis}"
      - "POSTGRES_USER=${POSTGRES_USER:-gis}"
      - "POSTGRES_DB=${POSTGRES_DB:-gis}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gis}"
    shm_size: 256MB
    volumes:
      - postgis_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    restart: unless-stopped
    expose:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  # -> Portainer
  portainer-data:
  # -> PostGIS data
  postgis_data:
  pgadmin_data: